// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqjwrlkkahsowicaeorr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxandybGtrYWhzb3dpY2Flb3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODgxMDUsImV4cCI6MjA2MzE2NDEwNX0.ZvPBa5vIPLDrqcWYJGiC5gtSYFHfMs24KYUWCsPUk9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);